# The name of your Pages project.
name = "topshelf"

# The date helps Cloudflare maintain backwards compatibility.
compatibility_date = "2025-08-14"

# This section configures your project as a static site.
# The "bucket" is the directory that contains your website's files.
bucket = "site"
